repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        pass_filenames: false

      - id: dprint
        name: dprint
        entry: uv run dprint fmt
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        pass_filenames: false

      - id: basedpyright
        name: basedpyright
        entry: uv run basedpyright
        language: system
        pass_filenames: false
