[project]
requires-python = ">=3.13"

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
exclude = [
    'tests/',
    '.venv/'
]
strict = true

[tool.isort]
profile = "black"
force_single_line = "true"
