"""2024 - Day 6 Part 1: Guard Gallivant"""

from textwrap import dedent

from src.year2024.day06a import solve


def test_solve():
    task = dedent(
        """
        ....#.....
        .........#
        ..........
        ..#.......
        .......#..
        ..........
        .#..^.....
        ........#.
        #.........
        ......#...
        """
    ).strip()
    assert solve(task) == 41
