name: main

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.15
          enable-cache: true

      - name: install project
        run: make install

      - name: lint
        run: make lint

      - name: format
        run: make ci-format

      - name: typecheck
        run: make typecheck

      - name: test
        run: make test
