name: main

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.18
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: install project
        run: uv sync --locked --all-extras --dev

      - name: lint
        run: uv run ruff check

      - name: format
        run: uv run ruff format --check --diff

      - name: typecheck
        run: uv run ty check

      - name: test
        run: uv run pytest tests
