name: main

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.13
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: lint
        run: |
          uv run ruff check --output-format=github
          uv run prek --all-files trailing-whitespace check-yaml debug-statements check-added-large-files

      - name: format
        run: |
          uv run dprint check
          uv run ruff format --check --diff

      - name: typecheck
        run: uv run basedpyright

      - name: test
        run: uv run pytest tests
